version: '3.8'

services:
  psql-db:
    image: postgres-${ENV}
    container_name: psql-db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    image: web-app-${ENV}
    container_name: frontend-${ENV}
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        VITE_APP_API_URL: ${VITE_APP_API_URL}
        VITE_NODE_ENV: ${VITE_NODE_ENV}
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: backend-${ENV}
    container_name: backend-${ENV}
    build:
      context: ./backend-forum
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
    name: db-data-volume-${ENV}
