version: '3.8'

services:
  psql-db:
    image: postgres-${ENV}
    container_name: psql-db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin7-${ENV}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      # Workaround for disabling pgAdmin docker logging (https://github.com/docker/compose/issues/8578)
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    logging:
      driver: none
    ports:
      - 5050:80
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  frontend:
    image: web-app-${ENV}
    container_name: frontend-${ENV}
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        VITE_APP_API_URL: ${VITE_APP_API_URL}
        VITE_NODE_ENV: ${VITE_NODE_ENV}
        VITE_APP_TITLE: Java forum
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    image: backend-${ENV}
    container_name: backend-${ENV}
    build:
      context: ./backend-forum
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_ERROR_INCLUDE-MESSAGE: always
      WEBAPP_ADMIN_USERNAME: ${WEBAPP_ADMIN_USERNAME}
      WEBAPP_ADMIN_USER_PASSWORD: ${WEBAPP_ADMIN_USER_PASSWORD}
    depends_on:
      - psql-db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
    name: db-data-volume-${ENV}
  pgadmin-data:
    name: db-pgadmin-volume-${ENV}
