version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=java-forum
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    image: web-app
    container_name: frontend
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        VITE_APP_API_URL: http://localhost:8080/api
        VITE_NODE_ENV: production
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend-forum
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/java-forum
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
    networks:
    - app-network

networks:
 app-network:

volumes:
  db-data: