CREATE OR REPLACE PROCEDURE clear_database()

LANGUAGE SQL

AS $$
    TRUNCATE TABLE tokens RESTART IDENTITY CASCADE;
    TRUNCATE TABLE users_ RESTART IDENTITY CASCADE;
    TRUNCATE TABLE boards RESTART IDENTITY CASCADE;
    TRUNCATE TABLE posts RESTART IDENTITY CASCADE;
    TRUNCATE TABLE topics RESTART IDENTITY CASCADE;
    TRUNCATE TABLE posts_users_ RESTART IDENTITY CASCADE;
$$;
