name: Run all tests

on:
  push:
  schedule:
    - 0 0 * * *
    - master

jobs:
  Update-production-server:
    name: Deploy to EC2 Production Server
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd forum/
            sh update-prod.sh
            exit
