name: Deploy to production

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  Deploy:
    name: Deploy to EC2 production server
    timeout-minutes: 30

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use SSH to connect EC2 and install production version
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd forum/
            sh update-prod.sh
            exit
