name: Run all tests

on:
  push:
    branches:
      - master
      - fix-pipeline
  pull_request:
    branches:
      - master

jobs:
  e2e-and-api-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Run backend api & unit tests
        run: mvn test -DargLine="-Dspring.profiles.active=test" --no-transfer-progress
        working-directory: ./backend-forum

      - name: Start checkout Cypress
        uses: actions/checkout@v3
      - name: Cypress run e2e tests against docker container
        uses: cypress-io/github-action@v5
        env:
          ELECTRON_EXTRA_LAUNCH_ARGS: "--disable-gpu"
          CYPRESS_baseUrl: http://localhost:80
        with:
          working-directory: web-app

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down -v

  Frontend-unit-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install project
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Create web-app build
        run: npm run build
