name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test_web_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app

    strategy:
      matrix:
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: npm ci
      - name: Run tests
        run: npm test
